### ISSUE TITLE
[BUG] module user without email attribute clears email

### ISSUE THREAD

**Issue by joernclausen** [Checkmk/ansible-collection-checkmk.general#304]
When using the user module without giving an email address, e.g. to augment an already present user with contact groups
```
tribe29.checkmk.user:
  name: "juser"
  contactgroups:
    - "webmaster"
```
the email field of the user in Checkmk gets emptied. IMHO in this case the email should not be modified and kept as is.
