### ISSUE TITLE
[BUG] Autodiscovery of services no longer works from version 2.1.0p21 through to 2.2.0b3

### ISSUE THREAD

**Issue by ashleykleynhans** [Checkmk/ansible-collection-checkmk.general#314]
**Describe the bug**

The `tribe29.checkmk.agent` role, has an option `checkmk_agent_discover` which last worked in version 2.1.0p20, but has not worked in any version since.

The host gets added to the CheckMk server, but the services are not automatically discovered and have to be discovered manually.

I tried this as a work-around but it only works sometimes, and not always, and also its annoying that when it does actually work, CheckMk first alerts that there are undiscovered services on the host before they are actually discovered by the tasks to discover the services and activate the changes.

```yml
  tasks:
    - name: Install CheckMK Agent
      ansible.builtin.include_role:
        name: tribe29.checkmk.agent

    - name: Discover Services
      tribe29.checkmk.discovery:
        server_url: "http://{{ checkmk_agent_server }}/"
        site: "{{ checkmk_agent_site }}"
        automation_user: "{{ checkmk_agent_user }}"
        automation_secret: "{{ checkmk_agent_pass }}"
        host_name: "{{ checkmk_agent_host_name }}"
        state: "fix_all"

    - name: Activate Changes
      tribe29.checkmk.activation:
        server_url: "http://{{ checkmk_agent_server }}/"
        site: "{{ checkmk_agent_site }}"
        automation_user: "{{ checkmk_agent_user }}"
        automation_secret: "{{ checkmk_agent_pass }}"
        force_foreign_changes: 'true'
      run_once: 'true'
```

**Component Name**

tribe29.checkmk.agent role/service discovery

**Ansible Version**

```console
$ ansible --version

ansible [core 2.14.4]
  config file = None
  configured module search path = ['/home/ubuntu/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/ubuntu/.cache/venv/ansible-3.10.5/lib/python3.10/site-packages/ansible
  ansible collection location = /home/ubuntu/.ansible/collections:/usr/share/ansible/collections
  executable location = /home/ubuntu/.cache/venv/ansible-3.10.5/bin/ansible
  python version = 3.10.6 (main, Aug  2 2022, 15:11:03) [GCC 7.5.0] (/home/ubuntu/.cache/venv/ansible-3.10.5/bin/python3)
  jinja version = 3.1.2
  libyaml = True
```

**Checkmk Version**

```console
2.2.0b3
```

**Collection Version**

```console
$ ansible-galaxy collection list

Collection        Version
----------------- -------
ansible.posix     1.4.0
community.general 6.5.0
tribe29.checkmk   0.20.0
```
**Environment**

**To Reproduce**

1. Run the following Ansible Playbook:

```yaml
---
- name: Playbook to install CheckMK Agent
  hosts: all
  gather_facts: yes

  vars:
    checkmk_agent_version: "{{ checkmk_global_version }}"
    checkmk_agent_edition: cre
    checkmk_agent_protocol: http
    checkmk_agent_server: example.com
    checkmk_agent_site: prod
    checkmk_agent_add_host: 'true'
    checkmk_agent_discover: 'true'
    checkmk_agent_update: 'true'
    checkmk_agent_configure_firewall: 'false'
    checkmk_agent_auto_activate: 'true'
    checkmk_agent_force_install: 'true'
    checkmk_agent_force_foreign_changes: 'true'
    checkmk_agent_host_name: "{{ lookup('env', 'CHECKMK_AGENT_HOST_NAME') }}"
    checkmk_agent_host_ip: "{{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}"

  tasks:
    - name: Install CheckMK Agent
      ansible.builtin.include_role:
        name: tribe29.checkmk.agent
```

2. Host is registered with the CheckMk server, but observe that services are not discovered automatically.

**Expected behavior**

Expect the services on the host to be discovered automatically and the changes to be activated on the CheckMk server.

**Actual behavior**

The services of the host are not automatically discovered and have to be discovered manually which is really painful.

**Additional context**

Happens in all versions from 2.1.0p21 through to 2.2.0b3 (inclusive).
Issue is not present if I roll back to 2.1.0p20.
