### ISSUE TITLE
[BUG] Folder name cannot be empty

### ISSUE THREAD

**Issue by robin-checkmk** [Checkmk/ansible-collection-checkmk.general#324]
**Describe the bug**

The module documentation states, that if no folder name is provided, it will fall back to extracting it from the folder path.
This does not work properly.

**Component Name**

`folder`

**Ansible Version**

```console
$ ansible --version
ansible [core 2.14.4]
  python version = 3.10.6 (main, Mar 10 2023, 10:55:28) [GCC 11.3.0] (/usr/bin/python3)
  jinja version = 3.1.2
  libyaml = True
```

**Checkmk Version**

```console
2.2.0b4 (CRE)
```

**Collection Version**

```console
$ ansible-galaxy collection list
Collection        Version
----------------- -------
tribe29.checkmk   0.21.0
```

**Environment**

**To Reproduce**
1. Define a folder without the `name` attribute.
2. Run the module.
3. See the error.

**Expected behavior**

The folder name is set to the last part of the path.

**Actual behavior**

The module crashes with the following error.
```console
PLAY [Debugging.] *************************************************************************************************************************************************************************************************

TASK [Gathering Facts] ********************************************************************************************************************************************************************************************
ok: [localhost]

TASK [Create folder.] *********************************************************************************************************************************************************************************************
fatal: [localhost]: FAILED! => {"changed": false, "msg": "Error calling API. HTTP code 400. Details: b'{\"title\": \"Bad Request\", \"status\": 400, \"detail\": \"These fields have problems: title\", \"fields\": {\"title\": [\"Field may not be null.\"]}}', "}

PLAY RECAP ********************************************************************************************************************************************************************************************************
localhost                  : ok=1    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0 
```

**Minimum reproduction example**

```yaml
---
- name: "Debugging."
  hosts: localhost
  tasks:
    - name: "Create folder."
      tribe29.checkmk.folder:
        server_url: "{{ checkmk_protocol }}://{{ checkmk_server }}:{{ checkmk_port }}/"
        site: "{{ checkmk_site }}"
        automation_user: "{{ checkmk_user }}"
        automation_secret: "{{ checkmk_pass }}"
        path: "/test"
```

**Additional context**
