### ISSUE TITLE
[BUG] downtime module doesn't assign a default downtime comment

### ISSUE THREAD

**Issue by stdevel** [Checkmk/ansible-collection-checkmk.general#350]
**Describe the bug**
According to [the documentation](https://github.com/Checkmk/ansible-collection-tribe29.checkmk/blob/main/plugins/modules/downtime.py#L38), the `downtime` module should pick a pre-defined downtime comment if none has been supplied. This is not working and the module prints the following error:

```command
TASK [Schedule host downtime] **************************************************
failed: [uyuni-client.giertz.loc -> localhost] (item=uyuni-client.giertz.loc) => {"ansible_loop_var": "item", "changed": false, "item": "uyuni-client.giertz.loc", "msg": "Error calling API while adding downtime for 'uyuni-client.giertz.loc' with comment 'None'. HTTP code 400.  Details: b'{\"title\": \"Bad Request\", \"status\": 400, \"detail\": \"These fields have problems: comment\", \"fields\": {\"comment\": [\"Field may not be null.\"]}}', "}
```

The workaround is to manually define an comment, e.g. like this:

```yaml
    - name: Schedule host downtime
      tribe29.checkmk.downtime:
        server_url: ...
        site: ...
        automation_user: ...
        automation_secret: ...
        host_name: ...
        start_after:
          seconds: 1
        end_after:
          hours: 4
        comment:
          description: Downtime for maintenance created by Ansible
```

**Component Name**

`downtime` module

**Ansible Version**

```console
$ ansible --version
ansible [core 2.14.1]
  config file = None
  configured module search path = ['/home/cstankow/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/cstankow/.local/lib/python3.11/site-packages/ansible
  ansible collection location = /home/cstankow/.ansible/collections:/usr/share/ansible/collections
  executable location = /home/cstankow/.local/bin/ansible
  python version = 3.11.3 (main, May 24 2023, 00:00:00) [GCC 13.1.1 20230511 (Red Hat 13.1.1-2)] (/usr/bin/python3)
  jinja version = 3.1.2
  libyaml = False
```

**Checkmk Version and Edition**

```console
Checkmk Raw Edition 2.1.0p18
```

**Collection Version**

```console
$ ansible-galaxy collection list
Collection                Version
------------------------- -------
tribe29.checkmk           0.22.0 
```

**To Reproduce**

1. Run a playbook like mentioned below
2. See error

**Expected behavior**

A default snapshot comment is assigned.

**Actual behavior**

The module aborts with an error.

**Minimum reproduction example**

```yaml
    - name: Schedule host downtime
      tribe29.checkmk.downtime:
        server_url: changeme
        site: test
        automation_user: changeme
        automation_secret: changeme
        host_name: changeme
        start_after:
          seconds: 1
        end_after:
          hours: 4

```

**Additional context**

Not applicable
