### ISSUE TITLE
[BUG] Discovery times out after upgrading from 2.2.0p1 to 2.2.0p3

### ISSUE THREAD

**Issue by ashleykleynhans** [Checkmk/ansible-collection-checkmk.general#367]
**Describe the bug**

I upgraded from 2.1.0.p1 to 2.1.0p3 and am now getting time out errors with Discovery.

```
fatal: [172.31.138.62 -> localhost]: FAILED! => {
    "changed": false,
    "invocation": {
        "module_args": {
            "automation_secret": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
            "automation_user": "automation",
            "host_name": "eventsdashboard-172-31-138-62",
            "server_url": "http://cmk-prod.snappic.xyz:80/",
            "site": "prod",
            "state": "fix_all",
            "validate_certs": true
        }
    },
    "msg": "-1 - Error calling API Details: Connection failure: timed out"
}
```

I also tried to upgrade tribe29.checkmk to checkmk.general 2.1.0 but still having the same issue.

**Component Name**

checkmk.general.discovery

**Ansible Version**

```console
$ ansible --version
ansible [core 2.14.4]
  config file = /home/ubuntu/ansible/ansible.cfg
  configured module search path = ['/home/ubuntu/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/ubuntu/.cache/venv/ansible-3.10.5/lib/python3.10/site-packages/ansible
  ansible collection location = /home/ubuntu/.ansible/collections:/usr/share/ansible/collections
  executable location = /home/ubuntu/.cache/venv/ansible-3.10.5/bin/ansible
  python version = 3.10.6 (main, Aug  2 2022, 15:11:03) [GCC 7.5.0] (/home/ubuntu/.cache/venv/ansible-3.10.5/bin/python3)
  jinja version = 3.1.2
  libyaml = True
```

**Checkmk Version and Edition**

```console
e.g. 2.1.0p3 (CRE)
```

**Collection Version**

```console
$ ansible-galaxy collection list
Collection        Version
----------------- -------
ansible.posix     1.4.0
checkmk.general   2.1.0
community.general 7.0.1
```

**To Reproduce**

1. Set appropriate variables for the playbook in the example below.
2. Run the Ansible playbook below.

**Expected behavior**

Services should be discovered and no API timeouts.

**Actual behavior**

I get an API timeout error:
```
fatal: [172.31.138.62 -> localhost]: FAILED! => {
    "changed": false,
    "invocation": {
        "module_args": {
            "automation_secret": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
            "automation_user": "automation",
            "host_name": "eventsdashboard-172-31-138-62",
            "server_url": "http://cmk-prod.snappic.xyz:80/",
            "site": "prod",
            "state": "fix_all",
            "validate_certs": true
        }
    },
    "msg": "-1 - Error calling API Details: Connection failure: timed out"
}
```

**Minimum reproduction example**

```yaml
---
- name: Playbook to install CheckMK Agent
  hosts: all
  gather_facts: yes

  vars:
    checkmk_agent_version: "{{ checkmk_global_version }}"
    checkmk_agent_edition: cre
    checkmk_agent_protocol: http
    checkmk_agent_server: cmk.example.com
    checkmk_agent_site: prod
    checkmk_agent_add_host: 'true'
    checkmk_agent_discover: 'true'
    checkmk_agent_update: 'true'
    checkmk_agent_configure_firewall: 'false'
    checkmk_agent_auto_activate: 'true'
    checkmk_agent_force_install: 'true'
    checkmk_agent_force_foreign_changes: 'true'
    checkmk_agent_host_name: "{{ lookup('env', 'CHECKMK_AGENT_HOST_NAME') }}"
    checkmk_agent_host_ip: "{{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}"

  tasks:
    - name: Install CheckMK Agent
      ansible.builtin.include_role:
        name: checkmk.general.agent

    - name: Discover Services
      checkmk.general.discovery:
        server_url: "http://{{ checkmk_agent_server }}/"
        site: "{{ checkmk_agent_site }}"
        automation_user: "{{ checkmk_agent_user }}"
        automation_secret: "{{ checkmk_agent_pass }}"
        host_name: "{{ checkmk_agent_host_name }}"
        state: "fix_all"

    - name: Activate Changes
      checkmk.general.activation:
        server_url: "http://{{ checkmk_agent_server }}/"
        site: "{{ checkmk_agent_site }}"
        automation_user: "{{ checkmk_agent_user }}"
        automation_secret: "{{ checkmk_agent_pass }}"
        force_foreign_changes: 'true'
      run_once: 'true'
```

**Additional context**

Ubuntu 22.04 LTS.
