### ISSUE TITLE
[BUG] Folder which ends with digit can not found

### ISSUE THREAD

**Issue by StratsScorpio** [Checkmk/ansible-collection-checkmk.general#379]
yml:
```
    - name: Create host at checkmk
      tribe29.checkmk.host:
        server_url: '{{ checkmk_server_url }}'
        site: '{{ checkmk_site }}'
        automation_user: '{{ cmkagent_reg_user }}'
        automation_secret: '{{ cmkagent_reg_password }}'
        host_name: '{{ inventory_hostname_short }}'
        folder: '{{ checkmk_host_folder }}'
        state: 'present'
```
`checkmk_host_folder: 'linux/fb1'`

> msg: 'Error calling API. HTTP code 400. Details: b''{"title": "Bad Request", "status": 400, "detail": "These fields have problems: folder", "fields": {"folder": ["The folder \''/linux/fb1\'' could not be found."]}}'', '

If I use something without digit like `'linux/fb'` it works. Yes, the folders are exists :wink:

**Comment by robin-checkmk** [comment]
Hi @StratsScorpio, I am missing a lot of information on your environment, as you did not use the bug report template.
From the playbook I can see, you are still using [the old collection name](https://forum.checkmk.com/t/we-are-renaming-the-checkmk-ansible-collection/38900). So I am assuming, you are not using the most up-to-date release.

It would help a lot, if you could provide some more context as we ask in the template. Thanks!

**Comment by StratsScorpio** [comment]
I've testet again with new collection, but the error is still here again:
inventory/host_vars/.../vars.yml:
```
# register against checkmk
vmdeploy_cmk_reg: 'yes'
checkmk_host_folder: 'linux/fb1'
```

 I've attached the role which will be called via adhoc-Script.

[cmk.zip](https://github.com/Checkmk/ansible-collection-checkmk.general/files/11936768/cmk.zip)

**Comment by msekania** [comment]
@StratsScorpio 

is folder '/linux/fb1' already present in the system?

The following works for me. CheckMK v 2.1p11, tribe29 0.22.0 (Will work with newer version also)

I am creating server `test` under `/test1/test2`.

1. create `/test1` folder
2. create '/test1/test2' folder
3. create server `test` under `/test1/test2` folder (which is already there)

```yaml
    - name: "Create single folder"
      tribe29.checkmk.folder:
        server_url: "https://{{ corr_site.server }}/"
        site: "{{ corr_site.site }}"
        automation_user: "{{ automation_user }}"
        automation_secret: "{{ automation_secret }}"
        path: '/test1'
        name: TEST1
        state: "present"
      run_once: true
      delegate_to: localhost

    - name: "Create single folder"
      tribe29.checkmk.folder:
        server_url: "https://{{ corr_site.server }}/"
        site: "{{ corr_site.site }}"
        automation_user: "{{ automation_user }}"
        automation_secret: "{{ automation_secret }}"
        path: '/test1/test2'
        name: TEST2
        state: "present"
      run_once: true
      delegate_to: localhost

    - name: "Create single host"
      tribe29.checkmk.host:
        server_url: "https://{{ corr_site.server }}/"
        site: "{{ corr_site.site }}"
        automation_user: "{{ automation_user }}"
        automation_secret: "{{ automation_secret }}"
        name: 'test'
        folder: '/test1/test2'
        state: "present"
      run_once: true
      delegate_to: localhost
```
