### ISSUE TITLE
[BUG] Refresh of agent data not working anymore with version 3.0.0 of ansible collection

### ISSUE THREAD

**Issue by DerLinkman** [Checkmk/ansible-collection-checkmk.general#414]
Verify first that your issue is not already reported [here](https://github.com/Checkmk/ansible-collection-checkmk.general/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc).
Where possible also test if the latest release and main branch are affected too.
Complete all sections as described!

**Describe the bug**
During the registration and installation of a new Agent it happens that the agent is refreshing it's data. In the Versions below 3.0.0 that worked flawlessly.
But with Version 3.0.0 it won't.

Logs of ansible playbook:
```
RUNNING HANDLER [checkmk.general.agent : Activate Changes.] **********************************************************************************************************************************************************************************************************************************************************
changed: [redacted.de -> localhost]

TASK [checkmk.general.agent : Register Agent for TLS.] ***************************************************************************************************************************************************************************************************************************************************************
changed: [redacted.de]

TASK [checkmk.general.agent : Fetch fresh monitoring data from the added host.] **************************************************************************************************************************************************************************************************************************************
fatal: [redacted.de -> localhost]: FAILED! => {"changed": false, "msg": "400 - Bad Request. Details: b'<!DOCTYPE HTML PUBLIC \"-//IETF//DTD HTML 2.0//EN\">\\n<html><head>\\n<title>400 Bad Request</title>\\n</head><body>\\n<h1>Bad Request</h1>\\n<p>Your browser sent a request that this server could not understand.<br />\\nReason: You\\'re speaking plain HTTP to an SSL-enabled server port.<br />\\n Instead use the HTTPS scheme to access this URL, please.<br />\\n</p>\\n<hr>\\n<address>Apache/2.4.57 (Debian) Server at ANSIBLE SERVER Port 80</address>\\n</body></html>\\n'"}
```

The curios thing is that the previous API Calls (registering a new host etc.) are working flawlessly. I even set https as the protocol to speak to the server.

**Component Name**

Component Name: agent

**Ansible Version**

```console
$ ansible --version
ansible [core 2.14.2]
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/root/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3/dist-packages/ansible
  ansible collection location = /root/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/bin/ansible
  python version = 3.10.12 (main, Jun 11 2023, 05:26:28) [GCC 11.4.0] (/usr/bin/python3)
  jinja version = 3.0.3
  libyaml = True
```

**Checkmk Version and Edition**

```console
2.2.0p7.(cre)
```

**Collection Version**

```console
$ ansible-galaxy collection list
# /root/.ansible/collections/ansible_collections
Collection        Version
----------------- -------
ansible.posix     1.4.0  
ansible.utils     2.9.0  
checkmk.general   3.0.0  
community.general 6.1.0 
```

**To Reproduce**
1. Activate Redirect of Apache2 with HTTPS Certificate for CheckMK (seen here: https://docs.checkmk.com/latest/en/omd_https.html)
2. Use the [example Playbook](https://github.com/Checkmk/ansible-collection-checkmk.general/blob/main/playbooks/usecases/remote-registration.yml) of checkmk.general.agent and fill it in with your own credentials
3. Execute the playbook

**Expected behavior**

With Versions prior to 3.0.0 it would register and refresh the monitoring data without any flaws.

**Actual behavior**

It still can register the host at the Server but it cannot refresh the monitoring data and exit the playbook with the error:

`fatal: [redacted.de -> localhost]: FAILED! => {"changed": false, "msg": "400 - Bad Request. Details: b'<!DOCTYPE HTML PUBLIC \"-//IETF//DTD HTML 2.0//EN\">\\n<html><head>\\n<title>400 Bad Request</title>\\n</head><body>\\n<h1>Bad Request</h1>\\n<p>Your browser sent a request that this server could not understand.<br />\\nReason: You\\'re speaking plain HTTP to an SSL-enabled server port.<br />\\n Instead use the HTTPS scheme to access this URL, please.<br />\\n</p>\\n<hr>\\n<address>Apache/2.4.57 (Debian) Server at ANSIBLE SERVER Port 80</address>\\n</body></html>\\n'"}`

In the Apache2 Logs i can see the following:

Working example:
```
v6_Redacted - - [16/Aug/2023:14:45:25 +0200] "GET //siteredacted/check_mk/api/1.0/objects/host_config/host.redacted.de?effective_attributes=true HTTP/1.1" 404 5797 "-" "ansible-httpget"
v6_Redacted - - [16/Aug/2023:14:45:25 +0200] "POST //siteredacted/check_mk/api/1.0/domain-types/host_config/collections/all HTTP/1.1" 200 7091 "-" "ansible-httpget"
v6_Redacted - - [16/Aug/2023:14:45:27 +0200] "POST /siteredacted/check_mk/api/1.0/domain-types/activation_run/actions/activate-changes/invoke HTTP/1.1" 200 6688 "-" "ansible-httpget"
v6_Redacted - - [16/Aug/2023:14:45:32 +0200] "GET //siteredacted/check_mk/api/1.0/version HTTP/1.1" 200 5962 "-" "ansible-httpget"
v6_Redacted - - [16/Aug/2023:14:45:32 +0200] "POST //siteredacted/check_mk/api/1.0/domain-types/service_discovery_run/actions/start/invoke HTTP/1.1" 200 19143 "-" "ansible-httpget"
v6_Redacted - - [16/Aug/2023:14:45:36 +0200] "POST /siteredacted/check_mk/api/1.0/domain-types/activation_run/actions/activate-changes/invoke HTTP/1.1" 200 6985 "-" "ansible-httpget"
v6_Redacted - - [16/Aug/2023:15:45:30 +0200] "GET //siteredacted/check_mk/api/1.0/objects/host_config/host.redacted.de?effective_attributes=true HTTP/1.1" 404 5797 "-" "ansible-httpget"
```

Broken example:
```
v6_Redacted - - [16/Aug/2023:15:45:30 +0200] "GET //siteredacted/check_mk/api/1.0/objects/host_config/host.redacted.de?effective_attributes=true HTTP/1.1" 404 5797 "-" "ansible-httpget"
v6_Redacted - - [16/Aug/2023:15:45:30 +0200] "POST //siteredacted/check_mk/api/1.0/domain-types/host_config/collections/all HTTP/1.1" 200 7091 "-" "ansible-httpget"
v6_Redacted - - [16/Aug/2023:15:45:32 +0200] "POST //siteredacted/check_mk/api/1.0/domain-types/activation_run/actions/activate-changes/invoke HTTP/1.1" 200 6696 "-" "ansible-httpget"
v6_Redacted - - [16/Aug/2023:15:45:36 +0200] "GET //siteredacted/check_mk/api/1.0/version HTTP/1.1" 200 5962 "-" "ansible-httpget"
v6_Redacted - - [16/Aug/2023:15:45:37 +0200] "GET //siteredacted/check_mk/api/1.0/objects/service_discovery_run/host.redacted.de/actions/wait-for-completion/invoke HTTP/1.1" 204 5607 "-" "ansible-httpget"
v6_Redacted - - [16/Aug/2023:15:45:37 +0200] "POST //siteredacted/check_mk/api/1.0/domain-types/service_discovery_run/actions/start/invoke HTTP/1.1" 302 5866 "-" "ansible-httpget"
v6_Redacted - - [16/Aug/2023:15:45:37 +0200] "GET / HTTP/1.0" 400 628 "-" "-"
```

**Minimum reproduction example**

```yaml
- name: "Register hosts against a remote site. With TLS."
  hosts: all
  strategy: linear
  vars:
    # Basic server and authentication information.
    # You have to provide the distributed setup yourself.
    checkmk_agent_version: "2.2.0p6"
    checkmk_agent_edition: "cre"
    checkmk_agent_user: "automation"
    checkmk_agent_pass: "REDACTED"
    # Here comes the part, where we get into remote registration
    checkmk_agent_protocol: https
    # The following should be set to the central site.
    # This where you configure the host objects.
    # Currently the agent package is also pulled from here.
    checkmk_agent_server: ANSIBLE SERVER
    checkmk_agent_site: "SITE"
    # The following should be pointed to the respective remote site.
    # This is where the registration will happen.
    checkmk_agent_registration_server: "{{ checkmk_agent_server }}"
    checkmk_agent_registration_site: "{{ checkmk_agent_site }}"
    # The folder might differ from your remote site name,
    # as it is the technical path. Check your configuration for this information.
    checkmk_agent_folder: "/FOLDER"
    # These options need to be enabled for all registrations to work.
    # You can however disable the one you do not want to perform.
    # But the host needs to be added and changes activated in any case.
    checkmk_agent_auto_activate: 'true'
    checkmk_agent_tls: 'true'
    checkmk_agent_add_host: 'true'
    # These are some generic agent options you might want to configure.
    checkmk_agent_discover: 'true'
    checkmk_agent_discover_max_parallel_tasks: 2
    checkmk_agent_force_install: 'true'
    checkmk_agent_delegate_api_calls: localhost
    checkmk_agent_delegate_download: "{{ inventory_hostname }}"
    checkmk_agent_host_name: "{{ inventory_hostname }}"
    checkmk_agent_host_folder: "{{ checkmk_agent_site }}"
    checkmk_agent_host_ip: "{{ ansible_host }}"
    checkmk_agent_host_attributes:
      ipaddress: "{{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}"
  roles:
    - checkmk.general.agent
```

**Additional context**

OS: All Servers (Ansible, CheckMK and Agent Node) are running on Debian 12
