### ISSUE TITLE
[FEED] Manage hosts: set Tags

### ISSUE THREAD

**Issue by StratsScorpio** [Checkmk/ansible-collection-checkmk.general#429]
**checkmk.general.host should have the option to set tags of this host**

We are using tag groups, like group OS-Family which contains different OS versions. A new created Host has default "NoOS", so I need update manually in Checkmk the host.

```
    - name: Create host at checkmk
      checkmk.general.host:
        server_url: '{{ checkmk_server_url }}'
        site: '{{ checkmk_site }}'
        automation_user: '{{ cmkagent_reg_user }}'
        automation_secret: '{{ cmkagent_reg_password }}'
        name: '{{ inventory_hostname_short }}'
        folder: '{{ checkmk_host_folder }}'
        state: 'present'
```

**Extension**
So lets add a section "tags" which contains a directoy listing. Search on host properties for this tag_key and select this (collection-)value. Also is possible, that the property has only a checkbox with true/false value.

If you can not set the tag_key or the collection has not this value, then error.

```
    - name: Create host at checkmk
      checkmk.general.host:
        server_url: '{{ checkmk_server_url }}'
        site: '{{ checkmk_site }}'
        automation_user: '{{ cmkagent_reg_user }}'
        automation_secret: '{{ cmkagent_reg_password }}'
        name: '{{ inventory_hostname_short }}'
        folder: '{{ checkmk_host_folder }}'
        state: 'present'
        tags:
            - '{{ tag_key }}': '{{ tag_value }}'
```
