### ISSUE TITLE
[BUG] Registering for TLS fails on distributed monitoring because of missing activation of changes

### ISSUE THREAD

**Issue by hb9hnt** [Checkmk/ansible-collection-checkmk.general#450]
This issue could be a duplicate of #442 - judging by its title. However it wasn't clear to me what the actual error in #442 was.

# Situation / Setup

We try to register the agent on another site than the main host, however the config and api is provided by the main host. Therefor we have two seperate site and server settings:

```yaml                                                                                                                                                                                                   checkmk_api_server: "main.example.com"                                                                                                                                                                                                                         
checkmk_api_site: "main_site"
checkmk_agent_server: "remote.example.com"                                                                                                                                                                                                                          
checkmk_agent_site: "remote_site"     
```

# Error

The TLS registration fails because changes haven't been activated yet and the host doesn't exit on the remote site, yet

```
_________________________________________________________
/ TASK [checkmk.general.agent : Linux: Register Agent for \
\ TLS.]                                                   /
 ---------------------------------------------------------
        \   ^__^
         \  (oo)\_______
            (__)\       )\/\
                ||----w |
                ||     ||
 
fatal: [newhost.example.com]: FAILED! => {"changed": true, "cmd": "cmk-agent-ctl register -H newshost.example.com-s remote.example.com -i remote_site -U cmkadmin -P ********** --trust-cert\n", "delta": "0:00:00.601492", "end": "2023-10-19 09:22:25.054996", "msg": "non-zero return code", "rc": 1, "start": "2023-10-19 09:22:24.453504", "stderr": "ERROR [cmk_agent_ctl] Error registering existing host at https://remote.example.com:8000/remote_n2017z1\n\nCaused by:\n    Request failed with code 404 Not Found: Host newhost.example.com does not exist.", "stderr_lines": ["ERROR [cmk_agent_ctl] Error registering existing host at https://remote.example.com:8000/remote_site", "", "Caused by:", "    Request failed with code 404 Not Found: Host newhost.example.com does not exist."], "stdout": "", "stdout_lines": []}
 ____________
```
(Sorry for the cow, I couldn't bring myself to deactivating them, yet.... And yes, I also have `sl` installed.. ;) )

# Fix / Workaround

If you flush the handlers - which at this point contain a activation of the changes - before registering TLS, this should work just fine. (I was only able to test it once...)

```diff
--- tasks/Linux.yml.bak 2023-10-19 11:27:00.086157277 +0200
+++ tasks/Linux.yml     2023-10-19 13:16:30.991360843 +0200
@@ -92,6 +92,10 @@
     and checkmk_agent_update | bool
     and (checkmk_agent_secret is defined and checkmk_agent_secret | length)
 
+- meta: flush_handlers
+- pause:
+    seconds: 30
+
 - name: "{{ ansible_system }}: Register Agent for TLS."  # noqa no-changed-when
   become: true
   ansible.builtin.shell: |
```

This way the changes including the new host are pushed to the remote site before registering the host for TLS.

EDIT: The workaround didn't work reliably because of a timing issue. I fixed this by adding a 30s pause, which is quite ugly TBH. Maybe you have a better idea how to solve this. For additional uglyness the pause is always executed, not only if changes are activated. :/
