### ISSUE TITLE
[BUG] tag_group module does not properly handle error

### ISSUE THREAD

**Issue by robin-checkmk** [Checkmk/ansible-collection-checkmk.general#481]
**Describe the bug**

The tag group module says `"msg": "Tag group created."`, although there is clearly an error.  
Full error message:
```console
fatal: [my_host.local]: FAILED! => {"changed": true, "http_code": 400, "info": {"body": "{\"title\": \"Bad Request\", \"status\": 400, \"detail\": \"These fields have problems: tags\", \"fields\": {\"tags\": [\"Tags IDs must be unique. You've used the following at least twice: 'cloud_provider_azure'\"]}}", "connection": "close", "content-length": "200", "content-security-policy": "default-src 'self' 'unsafe-inline' 'unsafe-eval' ssh: rdp:; img-src 'self' data: https://*.tile.openstreetmap.org/ ; connect-src 'self' https://crash.checkmk.com/ https://license.checkmk.com/api/verify; frame-ancestors 'self' ; base-uri 'self'; form-action 'self' javascript: 'unsafe-inline'; object-src 'self'; worker-src 'self' blob:", "content-type": "application/problem+json", "date": "Wed, 29 Nov 2023 12:46:38 GMT", "msg": "HTTP Error 400: BAD REQUEST", "permissions-policy": "accelerometer=(), autoplay=(), camera=(), encrypted-media=(), fullscreen=(), geolocation=(), gyroscope=(), magnetometer=(), microphone=(), midi=(), payment=(), picture-in-picture=(), usb=()", "referrer-policy": "origin-when-cross-origin", "server": "Apache", "status": 400, "url": "http://192.168.56.112//my_host/check_mk/api/1.0/domain-types/host_tag_group/collections/all", "x-content-type-options": "nosniff", "x-frame-options": "sameorigin", "x-permitted-cross-domain-policies": "none", "x-xss-protection": "1; mode=block"}, "msg": "Tag group created."}
```

**Component Name**

Component Name: tag_group

**Ansible Version**

```console
$ ansible --version
ansible [core 2.15.6]
```

**Checkmk Version and Edition**

```console
2.2.0p14 (CCE)
```

**Collection Version**

```console
$ ansible-galaxy collection list
checkmk.general               4.0.0
```

**To Reproduce**
1. Create a playbook that creates tag groups.
2. Use the same `id` twice.
3. See the error.

**Expected behavior**

The error message gets printed properly.

**Actual behavior**

The message indicates the tag_group was created, although it was not.

**Minimum reproduction example**

```yaml
  - name: "Configure Tag Cloud Provider."
    checkmk.general.tag_group:
      server_url: "{{ server_url }}"
      site: "{{ site }}"
      automation_user: "{{ automation_user }}"
      automation_secret: "{{ automation_secret }}"
      id: cloud_provider
      title: "Cloud Provider"
      topic: Tags
      choices:
        - id: cloud_provider_none
          title: None
        - id: cloud_provider_aws
          title: AWS
        - id: cloud_provider_azure
          title: Azure
        - id: cloud_provider_azure
          title: Azure
      state: present
```

**Additional context**
