### ISSUE TITLE
[BUG] Password module complains about required arguments, which are not actually required

### ISSUE THREAD

**Issue by robin-checkmk** [Checkmk/ansible-collection-checkmk.general#500]
**Describe the bug**

The password module behaves as if parameters are required, which are not required by the Checkmk REST API.

**Component Name**

Component Name: password

**Ansible Version**

```console
$ ansible --version
ansible [core 2.16.1]
```

**Checkmk Version and Edition**

```console
2.2.0p16 CCE
```

**Collection Version**

```console
$ ansible-galaxy collection list
Collection                    Version
----------------------------- -------
ansible.posix                 1.4.0  
checkmk.general               4.0.1  
community.general             5.5.0  
```

**To Reproduce**
1. Define a password, omitting e.g., the `documentation_url`.
2. Run the playbook
3. See the error under 'Actual behavior'.

**Expected behavior**

The password entry is created without the omitted parameters.

**Actual behavior**

```
failed: [host -> localhost] (item={'name': 'vsphere_ro', 'title': 'vSphere Read-Only User', 'password': 'topsecret1', 'comment': '2023-12-15T15:42:55Z Set by Ansible', 'owner': 'admin'}) => {"ansible_loop_var": "item", "changed": false, "item": {"comment": "2023-12-15T15:42:55Z Set by Ansible", "name": "vsphere_ro", "owner": "admin", "password": "topsecret1", "title": "vSphere Read-Only User"}, "msg": "400 - Bad Request: Parameter or validation failure. Details: b'{\"title\": \"Bad Request\", \"status\": 400, \"detail\": \"These fields have problems: documentation_url, shared\", \"fields\": {\"documentation_url\": [\"Field may not be null.\"], \"shared\": [\"Field may not be null.\"]}}'"}

```

**Minimum reproduction example**

```yaml
    - name: "Create Passwords."
      tags: [rules, config]
      checkmk.general.password:
        server_url: "{{ server_url }}"
        site: "{{ site }}"
        automation_user: "{{ automation_user }}"
        automation_secret: "{{ automation_secret }}"
      - name: "vsphere_ro"
        title: "vSphere Read-Only User"
        password: "topsecret1"
        comment: "{{ ansible_date_time.iso8601 }} Set by Ansible"
        owner: "admin"
        state: "present"
      delegate_to: localhost
      run_once: true  # noqa run-once[task]
      loop: "{{ checkmk_passwords }}"
```

**Additional context**
