### ISSUE TITLE
[BUG] `user` module complains about required arguments, which are not actually required

### ISSUE THREAD

**Issue by robin-checkmk** [Checkmk/ansible-collection-checkmk.general#520]
**Describe the bug**

The `user` module behaves as if parameters are required, which are not required by the Checkmk REST API.

**Component Name**

Component Name: user

**Ansible Version**

```console
$ ansible --version
ansible [core 2.16.1]
```

**Checkmk Version and Edition**

```console
2.2.0p17 CCE
```

**Collection Version**

```console
$ ansible-galaxy collection list
Collection                    Version
----------------------------- -------
ansible.posix                 1.4.0  
checkmk.general               4.1.0
community.general             5.5.0  
```

**To Reproduce**
1. Define a user, omitting e.g., the `fallback_contact`.
2. Run the playbook
3. See the error under 'Actual behavior'.

**Expected behavior**

The password entry is created without the omitted parameters.

**Actual behavior**

```
failed: [webinar.local -> localhost] (item={'name': 'webinar1', 'fullname': 'Mathias Kettner', 'email': 'info@checkmk.com', 'pager': '+4989998209700', 'roles': ['user'], 'language': 'en'}) => {"ansible_loop_var": "item", "changed": false, "item": {"email": "info@checkmk.com", "fullname": "Mathias Kettner", "language": "en", "name": "webinar1", "pager": "+4989998209700", "roles": ["user"]}, "msg": "[create_user] Error calling API. HTTP code 400. Details: b'{\"title\": \"Bad Request\", \"status\": 400, \"detail\": \"These fields have problems: contact_options\", \"fields\": {\"contact_options\": {\"fallback_contact\": [\"Field may not be null.\"]}}}', , log: module.params: {'name': 'webinar1', 'fullname': 'Mathias Kettner', 'roles': ['user'], 'language': 'en', 'email': 'info@checkmk.com', 'pager_address': '+4989998209700', 'state': 'present', 'validate_certs': True, 'customer': None, 'password': None, 'enforce_password_change': None, 'auth_type': None, 'disable_login': None, 'fallback_contact': None, 'idle_timeout_duration': None, 'idle_timeout_option': None, 'authorized_sites': None, 'contactgroups': None, 'disable_notifications': None} § desired_user: User(name: webinar1, state: present, attributes: {'disable_login': False, 'contact_options': {'email': 'info@checkmk.com', 'fallback_contact': None}, 'idle_timeout': {'option': 'global'}, 'roles': ['user'], 'contactgroups': [], 'pager_address': '+4989998209700', 'disable_notifications': {}, 'username': 'webinar1', 'fullname': 'Mathias Kettner', 'language': 'en'}, etag: None) § current_user: User(name: webinar1, state: absent, attributes: {}, etag: )"}
```

**Minimum reproduction example**

```yaml
    ## Needs support for user interface options
    - name: "Manage Users."
      checkmk.general.user:
        server_url: "{{ server_url }}"
        site: "{{ site }}"
        automation_user: "{{ automation_user }}"
        automation_secret: "{{ automation_secret }}"
        name: "{{ item.name }}"
        fullname: "{{ item.fullname | default(omit) }}"
        # interface_options: "{{ item.interface_options | default(omit) }}"
        roles: "{{ item.roles | default(omit) }}"
        language: "{{ item.language | default(omit) }}"
        email: "{{ item.email | default(omit) }}"
        pager_address: "{{ item.pager | default(omit) }}"
        state: "present"
      delegate_to: localhost
      run_once: true  # noqa run-once[task]
      loop: "{{ checkmk_users }}"
```

**Additional context**

#500 showed the same behavior. Maybe we should review all modules for this kind of behavior.
