### ISSUE TITLE
[BUG] value_raw is translated wrongly while creating a rule with checkmk.general.rule:

### ISSUE THREAD

**Issue by Mik3yZ** [Checkmk/ansible-collection-checkmk.general#523]
**Describe the bug**
We are creating rules via a loop, with a vars file. The code for creating the rule:

```yaml
- name: "Create global rule for in main folder"
  delegate_to: localhost
  checkmk.general.rule:
    automation_secret: "{{ automation_secret }}"
    automation_user: "{{ automation_user }}"
    rule:
      conditions: "{{ item.rule.conditions }}"
      properties:
        description: "{{ item.rule.properties.description }}"
        comment: "{{ item.rule.properties.comment | default() }}"
        disabled: "{{ item.rule.properties.disabled | default(False) }}"
        documentation_url: "https://sharepoint.website/onenote_notebook/page_something"
      value_raw: "{{ item.rule.value_raw }}"
      location: "{{ item.rule.location }}"
    ruleset: "{{ item.ruleset }}"
    server_url: "{{ master_site_baseurl }}"
    site: "{{ master_site }}"
  loop: "{{ rulesets | flatten(levels=1) }}"
  loop_control:
    label: "{{ item.ruleset }} [{{ item.rule.properties.description | default() }}]"
```

The item from the loop that fails:

```yaml
- - rule:
      conditions:
        host_labels: []
        host_tags:
        - key: g_t_discovery
          operator: is
          value: g_t_discovery_enabled_ssl_auto
        - key: g_t_host_check_command
          operator: none_of
          value:
          - g_t_hcc_ping
          - g_t_hcc_alwaysup
          - g_t_hcc_always_offline
        service_labels: []
      location:
        folder: /
      properties:
        description: Automatically activate SSL certficate changes (remove/add)
      value_raw: "{'check_interval': 120.0, 'inventory_rediscovery': {'activation': True, 'excluded_time': [], 'group_time': 300, 'mode': 2, 'service_filters': ('combined', {'service_whitelist': ['^SSL.*']})}, 'severity_new_host_label': 1, 'severity
_unmonitored': 1, 'severity_vanished': 0}"
    ruleset: periodic_discovery
```

When we run this with -vvv we can see the issue happening, value_raw becomes:

```yaml
"value_raw": "{'check_interval': 120.0, 'inventory_rediscovery': {'activation': True, 'excluded_time': [], 'group_time': 300, 'mode': 2, 'service_filters': ['combined', {'service_whitelist': ['^SSL.*']}]}, 'severity_new_host_label': 1, 'severity_unmonitored': 1, 'severity_vanished': 0}"
```
The issue is actually with the **(** and **)** in the service_filters. They get changed to **[** and **]**

**Component Name**
Component Name: rule

**Ansible Version**

```console
$ ansible --version
ansible [core 2.14.13]
  config file = /home/user/repos/CheckMK/ansible.cfg
  configured module search path = ['/home/user/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/user/venvs/ansible-checkmk/lib64/python3.9/site-packages/ansible
  ansible collection location = /home/user/.ansible/collections:/usr/share/ansible/collections
  executable location = /home/user/venvs/ansible-checkmk/bin/ansible
  python version = 3.9.16 (main, May 29 2023, 00:00:00) [GCC 11.3.1 20221121 (Red Hat 11.3.1-4)] (/home/user/venvs/ansible-checkmk/bin/python3)
  jinja version = 3.1.2
  libyaml = True

```

**Checkmk Version and Edition**
```console
Checkmk Enterprise Edition 2.2.0p16
```

**Collection Version**
```console
$ ansible-galaxy collection list
...
Collection             Version
---------------------- -------
ansible.posix          1.5.4  
brocade.fos            1.3.3  
checkmk.general        4.0.0  
community.general      7.0.1  
community.vmware       3.3.0  
ibm.power_aix          1.7.2  
ibm.power_hmc          1.8.1  
ibm.power_vios         1.3.0  
ibm.storage_virtualize 2.1.0  
kubernetes.core        2.3.2  
seancallaway.rancher   0.2.1  
tribe29.checkmk        0.22.0
```

**To Reproduce**
Steps to reproduce the behavior kind of described in the description above.

**Expected behavior**
The rule gets created, the ( and ) don't get translated / replaced in the value_raw.

**Actual behavior**
Rule creation fails, the ( and ) get translated / replaced in the value_raw.
