### ISSUE TITLE
[BUG] update_attributes on folder with network scan enabled (and a network scan result present) fails

### ISSUE THREAD

**Issue by Mik3yZ** [Checkmk/ansible-collection-checkmk.general#531]
**Describe the bug**
When a network scan is defined and a result is there for a folder, we can't update the folder attributes.
```
failed: [RemoteTest1 -> localhost] (item={'name': 'Graveyard', 'path': 'graveyard', 'contactgroups': ['g_cg_windowsengineers', 'g_cg_linuxengineers', 'g_cg_vmwareengineers', 'g_cg_hypervengineers', 'g_cg_networkengineers']}) => {"ansible_loop_var": "item", "changed": false, "item": {"contactgroups": ["g_cg_windowsengineers", "g_cg_linuxengineers", "g_cg_vmwareengineers", "g_cg_hypervengineers", "g_cg_networkengineers"], "name": "Graveyard", "path": "graveyard"}, "msg": "Error calling API. HTTP code 400. Details: b'{\"title\": \"Bad Request\", \"status\": 400, \"detail\": \"These fields have problems: update_attributes\", \"fields\": {\"update_attributes\": {\"network_scan_result\": [\"Not a string, but a dict\", \"Tag group name must start with \\'tag_\\'\", \"Unknown field.\"]}}}', "}
```

**Component Name**
Component Name: folder_module

**Ansible Version**

```console
$ ansible --version
ansible [core 2.14.13]
  config file = /home/<uid>/repos/ansible-checkmk/ansible.cfg
  configured module search path = ['/home/<uid>/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/<uid>/venvs/ansible-checkmk/lib64/python3.9/site-packages/ansible
  ansible collection location = /home/<uid>/.ansible/collections:/usr/share/ansible/collections
  executable location = /home/<uid>/venvs/ansible-checkmk/bin/ansible
  python version = 3.9.16 (main, May 29 2023, 00:00:00) [GCC 11.3.1 20221121 (Red Hat 11.3.1-4)] (/home/<uid>/venvs/ansible-checkmk/bin/python3)
  jinja version = 3.1.2
  libyaml = True
```

**Checkmk Version and Edition**

```console
Checkmk Enterprise Edition 2.2.0p17
```

**Collection Version**

```console
$ ansible-galaxy collection list
...
checkmk.general        4.0.0
...
```

**To Reproduce**

We create our folder structure via a var file:
``` yaml
---
folders:
  - { name: "Graveyard", path: "graveyard", contactgroups: [ "g_cg_windowsengineers", "g_cg_linuxengineers", "g_cg_vmwareengineers", "g_cg_hypervengineers", "g_cg_networkengineers" ] }
```

And we then create the folders with a loop.
``` yaml
---
- name: Include vars of folders.yml
  ansible.builtin.include_vars:
    file: vars/folders.yml

- name: "Create folders"
  checkmk.general.folder:
    server_url: "{{ master_site_baseurl }}"
    site: "{{ master_site }}"
    automation_user: "{{ automation_user }}"
    automation_secret: "{{ automation_secret }}"
    path: "{{ folder_basepath }}/{{ item.path.lower() }}"
    name: "{{ item.name }}"
    update_attributes:
      labels: "{{ item.labels|default(omit) }}"
    state: "{{ item.state | default('present') }}"
  delegate_to: localhost
  loop: "{{ folders }}"

- name: "Update folder contactgroups"
  checkmk.general.folder:
    server_url: "{{ master_site_baseurl }}"
    site: "{{ master_site }}"
    automation_user: "{{ automation_user }}"
    automation_secret: "{{ automation_secret }}"
    path: "{{ folder_basepath }}/{{ item.path.lower() }}"
    name: "{{ item.name }}"
    update_attributes:
      contactgroups:
        groups: "{{ item.contactgroups }}"
        use: true
        use_for_services: true
        recurse_use: true
        recurse_perms: true
    state: "{{ item.state | default('present') }}"
  delegate_to: localhost
  loop: "{{ folders }}"
  when: item.contactgroups is defined
```

The first time this runs succesfully, but when we define a network scan on this folder (and wait for it to finish so a network scan result is there) and run the playbook we receive the failure on the "Update folder contactgroups" play:

```
failed: [RemoteTest1 -> localhost] (item={'name': 'Graveyard', 'path': 'graveyard', 'contactgroups': ['g_cg_windowsengineers', 'g_cg_linuxengineers', 'g_cg_vmwareengineers', 'g_cg_hypervengineers', 'g_cg_networkengineers']}) => {"ansible_loop_var": "item", "changed": false, "item": {"contactgroups": ["g_cg_windowsengineers", "g_cg_linuxengineers", "g_cg_vmwareengineers", "g_cg_hypervengineers", "g_cg_networkengineers"], "name": "Graveyard", "path": "graveyard"}, "msg": "Error calling API. HTTP code 400. Details: b'{\"title\": \"Bad Request\", \"status\": 400, \"detail\": \"These fields have problems: update_attributes\", \"fields\": {\"update_attributes\": {\"network_scan_result\": [\"Not a string, but a dict\", \"Tag group name must start with \\'tag_\\'\", \"Unknown field.\"]}}}', "}
```

**Expected behavior**
We expect the folder to just be updated

**Actual behavior**
Error message
