### ISSUE TITLE
[BUG] folder creation always lowers the foldername

### ISSUE THREAD

**Issue by Mik3yZ** [Checkmk/ansible-collection-checkmk.general#569]
**Describe the bug**
When creating a folder with uppercase letters, the folder.py changes it to lowercase.

**Component Name**
Component Name: folder

**Ansible Version**
```console
$ ansible --version
ansible [core 2.14.13]
  config file = /home/user/repos/ansible-checkmk/ansible.cfg
  configured module search path = ['/home/user/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/user/venvs/ansible-checkmk/lib64/python3.9/site-packages/ansible
  ansible collection location = /home/user/.ansible/collections:/usr/share/ansible/collections
  executable location = /home/user/venvs/ansible-checkmk/bin/ansible
  python version = 3.9.16 (main, May 29 2023, 00:00:00) [GCC 11.3.1 20221121 (Red Hat 11.3.1-4)] (/home/user/venvs/ansible-checkmk/bin/python3)
  jinja version = 3.1.2
  libyaml = True
```

**Checkmk Version and Edition**
```console
Checkmk Enterprise Edition 2.2.0p20
```

**Collection Version**

```console
$ ansible-galaxy collection list | grep checkmk.general
checkmk.general        4.3.1  
```

**To Reproduce**
Create a folder with:
``` yml
- name: "Create folder"
  checkmk.general.folder:
    server_url: "{{ master_site_baseurl }}"
    site: "{{ master_site }}"
    automation_user: "{{ automation_user }}"
    automation_secret: "{{ automation_secret }}"
    path: "/foldername"
    name: "FolderName"
    state: "present"
```

**Expected behavior**
A folder named FolderName, with path /foldername 

**Actual behavior**
A folder named foldername with path /foldername

**Minimum reproduction example**
See above

**Additional context**
`folder.py` contains:

https://github.com/Checkmk/ansible-collection-checkmk.general/blob/300764eaccd4b744908eb5415b9735a86d540d57/plugins/modules/folder.py#L220-L221

And this function (`_normalize_path`) changes the string to lowercase:

https://github.com/Checkmk/ansible-collection-checkmk.general/blob/300764eaccd4b744908eb5415b9735a86d540d57/plugins/modules/folder.py#L274-L278

I would advise to not normalize the name / title as a path.
