### ISSUE TITLE
[BUG] `discovery` module out of sync with the Checkmk REST API

### ISSUE THREAD

**Issue by robin-checkmk** [Checkmk/ansible-collection-checkmk.general#587]
**Describe the bug**

The `discovery` module reports the following error, when run in `bulk_mode`.
`fatal: [host -> localhost]: FAILED! => {"changed": false, "msg": "State 'tabula_rasa' does not exist in bulk_discovery, please use refresh!"}`
But this is not true as of now. We have to double-check this.

On top of that, with Checkmk 2.3.0 a new approach to service discovery is implemented and while the old options stay  for now, they are deprecated.

So the bare minimum we need to do, is to fix the above issue. Ideally we directly update the module to use the new options for Checkmk 2.3.0.

**Component Name**

Component Name: discovery

**Ansible Version**

```console
$ ansible --version

```

**Checkmk Version and Edition**

```console
2.3.0b3 CRE
```

**Collection Version**

```console
$ ansible-galaxy collection list

```

**To Reproduce**
1. Create a task to discover services on a host.
2. Use `tabula_rasa` as the `state`.
3. See the error mentioned above.

**Expected behavior**

The `discovery` module behaves analogue to the REST API endpoints.

**Actual behavior**

`fatal: [host -> localhost]: FAILED! => {"changed": false, "msg": "State 'tabula_rasa' does not exist in bulk_discovery, please use refresh!"}`

**Minimum reproduction example**

```yaml
- name: "Discover services in bulk mode."
  checkmk.general.discovery:
    server_url: "{{ server_url }}"
    site: "{{ site }}"
    automation_user: "{{ automation_user }}"
    automation_secret: "{{ automation_secret }}"
    hosts: "{{ play_hosts }}"
    bulk_size: 20
    state: "tabula_rasa"
  delegate_to: localhost
  run_once: true  # noqa run-once[task]
```

**Additional context**
