### ISSUE TITLE
[BUG] Skip verifying the ssl cert for setting downtimes

### ISSUE THREAD

**Issue by peterge-misoft** [Checkmk/ansible-collection-checkmk.general#641]
Verify first that your issue is not already reported [here](https://github.com/Checkmk/ansible-collection-checkmk.general/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc).
Where possible also test if the latest release and main branch are affected too.
Complete all sections as described!

**Describe the bug**
![image](https://github.com/user-attachments/assets/9ba475cd-a645-4efb-8605-4ec0f11c4843)

**Component Name**

Component Name: downtime

**Ansible Version**

```console
ansible [core 2.16.8]

```

**Checkmk Version and Edition**

```console
2.3.0p10
```

**Collection Version**

```console
$ ansible-galaxy collection list
checkmk.general                          5.1.0
```

**To Reproduce**
write a playbook with such a downtime task.

**Expected behavior**

set downtime

**Actual behavior**

ssl error

**Minimum reproduction example**

```yaml
    - name: "Downtime 4 - on host with relative times"
      downtime:
        server_url: "{{ checkmk_var_server_url }}"
        site: "{{ checkmk_var_site }}"
        automation_user: "{{ checkmk_var_automation_user }}"
        automation_secret: "{{ checkmk_var_automation_secret }}"
        host_name: "{{ item }}"
        comment: downtime scheduled by auto-update-ci
        start_after:
          hours: 0
          minutes: 0
        end_after:
          hours: 3
          minutes: 0
      delegate_to: localhost
      with_items:
        - gitlab.misoft.lan
        - miprdvaultwarden.misoft.lan
        - miprdbookstack.misoft.lan
        - miprdnetbox.misoft.lan
        - npm.misoft.lan
        - miprdhomeassistant.misoft.lan
        - miprdnextcloud.misoft.lan
```

**Additional context**
it works fine on my workstation but doesnt in ci pipeline (the container does not have the cert). But here should be a var similar to checkmk_agent_server_validate_certs.
