### ISSUE TITLE
[BUG] Special characters in password break TLS agent registration

### ISSUE THREAD

**Issue by schnoddelbotz** [Checkmk/ansible-collection-checkmk.general#740]
**Describe the bug**
Using a special character (here: &) in a password currently breaks [Register Agent for TLS directly](https://github.com/Checkmk/ansible-collection-checkmk.general/blob/main/roles/agent/tasks/Linux.yml#L143) task.

**Component Name**
Component Name: registration

**Ansible Version**

```console
$ ansible --version
ansible [core 2.18.3]
```

**Checkmk Version and Edition**

```console
2.3.0p27 (CRE)
```

**Collection Version**

```console
$ ansible-galaxy collection list
Collection                               Version
---------------------------------------- -------
checkmk.general                          5.6.0
```

**To Reproduce**
1. Set var `checkmk_agent_secret` of `checkmk.general.agent` role to `f00<bar&baz?bli`
2. Run playbook with `checkmk_agent_no_log` set to `false`
3. See error:
```console
TASK [checkmk.general.agent : Linux: Register Agent for TLS directly.] *****************************************************
fatal: [logs]: FAILED! => {"changed": false, "cmd": "cmk-agent-ctl register -H logs -s 10.65.26.209 
-i mysite -U cmkadmin -P f00<bar&baz?bli --trust-cert\n", "delta": "0:00:00.003291", 
"end": "2025-03-04 13:39:02.397502", "msg": "non-zero return code", "rc": 127, 
"start": "2025-03-04 13:39:02.394211", 
"stderr": "/bin/sh: 1: : baz?bli not found\n/bin/sh: 1: cannot open bar: No such file", 
"stderr_lines": ["/bin/sh: 1: baz?bli: not found", "/bin/sh: 1: cannot open bar: No such file"], 
"stdout": "", "stdout_lines": []}
```

**Expected behavior**

Expected special characters in password to be accepted.

**Actual behavior**

Error above.

**Minimum reproduction example**

```yaml
- name: "Install checkmk agent"
  ansible.builtin.include_role:
    name: checkmk.general.agent
  vars:
    checkmk_agent_secret: "f00<bar&baz?bli"
    ....
```

**Additional context**
Quoting the password using [ansible.builtin.quote](https://docs.ansible.com/ansible/latest/collections/ansible/builtin/quote_filter.html) in
[roles/agents/task/Linux.yml](https://github.com/Checkmk/ansible-collection-checkmk.general/blob/main/roles/agent/tasks/Linux.yml#L148)
fixed the issue for me:

```yaml
- name: "{{ ansible_system }}: Register Agent for TLS directly."
  become: true
  ansible.builtin.shell: |
    cmk-agent-ctl register -H {{ checkmk_agent_host_name }} \
    -s {{ checkmk_agent_registration_server }} -i {{ checkmk_agent_registration_site }} \
    -U {{ checkmk_agent_user }} -P {{ __checkmk_agent_auth | ansible.builtin.quote }} --trust-cert
```
Note the issue also affects (at least) `Register Agent for TLS with proxy-register` task.
