### ISSUE TITLE
[BUG] checkmk_agent_delegate_download to localhost for windows target won't work

### ISSUE THREAD

**Issue by MaximilianClemens** [Checkmk/ansible-collection-checkmk.general#741]
**Describe the bug**
When `checkmk_agent_delegate_download` is set to `localhost` and the target is a Windows system, the download tasks use a Windows path (e.g., `C:\Windows\Temp\check-mk-agent_2.3.0p25.msi`). This causes the download to fail, and the issue goes unnoticed because the `failed_when` condition is set to false. A potential fix would be to introduce a new setting (e.g., `checkmk_agent_delegate_download_path`) that downloads the file into a Linux-compatible directory, which is then copied to the correct Windows location.

**Component Name**
role.agent > Win32NT-files.yml > Download Tasks

**Ansible Version**
```console
ansible [core 2.16.2]
  config file = None
  configured module search path = ['/home/xclemens/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/xclemens/.local/lib/python3.10/site-packages/ansible
  ansible collection location = /home/xclemens/.ansible/collections:/usr/share/ansible/collections
  executable location = /home/xclemens/.local/bin/ansible
  python version = 3.10.12 (main, Feb  4 2025, 14:57:36) [GCC 11.4.0] (/usr/bin/python3)
  jinja version = 3.0.3
  libyaml = True

```

**Checkmk Version and Edition**
```console
Checkmk Enterprise Edition 2.3.0p25
```

**Collection Version**

```console
$ ansible-galaxy collection list
checkmk.general                      5.6.0  
```

**To Reproduce**
1. Set checkmk_agent_delegate_download to localhost on a Linux control node.
2. Target a Windows system.
3. Run the playbook to download the agent.
4. The agent download fails because the destination path (C:\...) does not exist on Linux.

**Expected behavior**
The agent should be downloaded to a Linux-compatible temporary directory (e.g., using a new setting like checkmk_agent_delegate_download_path) and then copied to the correct Windows location.

**Actual behavior**
Nothing is downloaded because the destination path is invalid on Linux, and the error is hidden due to failed_when being set to false.

**Additional context**
Affected Lines:
[Win32NT-files.yml Lines 177C1-L225C27](https://github.com/Checkmk/ansible-collection-checkmk.general/blob/2188a6dc031a021ba9148e77877b002dcb82b41d/roles/agent/tasks/Win32NT-files.yml#L177C1-L225C27)

**Possible Solution, not ready (!) just a idea for the direction**
```yaml
- name: "{{ ansible_system }}: Download GENERIC {{ checkmk_agent_edition | upper }} Agent (delegated)."
  ansible.builtin.uri:
    url: "{{ __checkmk_agent_agent.url.cee }}?\
          os_type={{ __checkmk_agent_files_mapping[ansible_os_family] }}&\
          agent_type=generic"
    validate_certs: "{{ checkmk_agent_server_validate_certs | bool }}"
    dest: "{{ checkmk_agent_delegate_download_path }}/{{ inventory_hostname }}-check-mk-agent_{{ checkmk_agent_version }}.msi"
    method: GET
    headers:
      Authorization: "Bearer {{ checkmk_agent_user }} {{ __checkmk_agent_auth }}"
      Accept: "application/octet-stream"
  when: |
    checkmk_agent_edition | lower != "cre"
    and not (checkmk_agent_host_specific | bool or checkmk_agent_folder_specific | bool)
  retries: 3
  delegate_to: "{{ checkmk_agent_delegate_download }}"
  tags:
    - download-package

- name: "{{ ansible_system }}: Transfer host-specific {{ checkmk_agent_edition | upper }} Agent."
  ansible.windows.win_copy:
    src: "{{ checkmk_agent_delegate_download_path }}/{{ inventory_hostname }}-check-mk-agent_{{ checkmk_agent_version }}.msi"
    dest: "{{ __checkmk_agent_agent.file.host }}"
  when: |
    checkmk_agent_edition | lower != "cre"
    and checkmk_agent_host_specific | bool
  tags:
    - download-package

- name: "{{ ansible_system }}: Transfer GENERIC or folder-specific {{ checkmk_agent_edition | upper }} Agent."
  ansible.windows.win_copy:
    src: "{{ checkmk_agent_delegate_download_path }}/check-mk-agent_{{ checkmk_agent_version }}.msi"
    dest: "{{ __checkmk_agent_agent.file.cee }}"
  when: |
    checkmk_agent_edition | lower != "cre"
    and not checkmk_agent_host_specific | bool
  tags:
    - download-package

- name: "{{ ansible_system }}: Transfer Vanilla {{ checkmk_agent_edition | upper }} Agent."
  ansible.windows.win_copy:
    src: "{{ checkmk_agent_delegate_download_path }}/check-mk-agent_{{ checkmk_agent_version }}.msi"
    dest: "{{ __checkmk_agent_agent.file.cre }}"
  when: |
    checkmk_agent_edition | lower == "cre"
  tags:
    - download-package

```
