### ISSUE TITLE
[BUG] Conflict updating a host's attributes while moving it to another folder

### ISSUE THREAD

**Issue by eliasp** [Checkmk/ansible-collection-checkmk.general#743]
**Describe the bug**
Updating attributes of a host and updating its folder at the same time fails.

**Component Name**
Component Name: agent

**Ansible Version**
```console
$ ansible --version
ansible [core 2.15.13]
  config file = None
  configured module search path = ['/tmp/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.9/site-packages/ansible
  ansible collection location = /tmp/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/local/bin/ansible
  python version = 3.9.21 (main, Dec  5 2024, 00:00:00) [GCC 11.5.0 20240719 (Red Hat 11.5.0-2)] (/usr/bin/python3)
  jinja version = 3.1.5
  libyaml = True
```

**Checkmk Version and Edition**
```console
e.g. 2.2.0p26 (CRE)
```

**Collection Version**
```console
$ ansible-galaxy collection list
# /usr/share/ansible/collections/ansible_collections                                                                                                                                       Collection                Version
------------------------- -------
ansible.posix             1.5.4
ansible.utils             5.0.0
checkmk.general           5.6.0
community.general         9.2.0
community.vmware          4.5.0
containers.podman         1.16.3
fedora.linux_system_roles 1.84.1
freeipa.ansible_freeipa   1.13.2
onepassword.connect       2.3.0
```

**To Reproduce**
1. Write a playbook which uses `ansible.builtin.include_role` to execute the `checkmk.general.agent` role
2. Set at least the variables `checkmk_agent_folder` and `checkmk_agent_host_ip`
3. Move the targeted host to another folder than the one defined in `checkmk_agent_folder`
4. Execute the playbook
5. The execution aborts at the task `Create host on server.` with the following error:
```JSON
{
  "changed": false,
  "failed_when_result": true,
  "msg": "ERROR: The folder parameter is different from the folder in which the host is located, while other parameters are also specified!\n                     If you want to move the host to a specific folder, please omit the other parameters:                     'attributes', 'update_attributes' and 'remove_attributes'."
}
```
**Expected behavior**
I'd expect `checkmk.general.agent` to handle this conflict transparently:
- move the host to the target folder
- then apply the conflicting changes to attributes

**Actual behavior**
Due to a bug in Checkmk, where the deletion of a host doesn't invalidate its DNS cache, I have to set the host's IP explicitly via `checkmk_agent_host_ip`.
This adds the IP to `checkmk_agent_host_attributes`, which in turn is passed as `attributes` to the module `checkmk.general.host`.

The Checkmk REST API apparently doesn't allow to modify a host's attributes at the same time as updating a host's folder and returns the corresponding error.

**Minimum reproduction example**
`playbook_checkmk.yml`:
```yaml
---
- name: Debug the Checkmk role
  hosts: [REDACTED]
  tasks:
    - name: Configure firewall to allow inbound connections to Checkmk agent
      ansible.posix.firewalld:
        immediate: true
        permanent: true
        state: enabled
        service: checkmk-agent
    - name: Set vars for `checkmk.general.agent`
      ansible.builtin.set_fact:
        checkmk_agent_add_host: true
        checkmk_agent_auto_activate: true
        checkmk_agent_discover: true
        checkmk_agent_edition: cre
        checkmk_agent_folder: /pipeline/systems
        checkmk_agent_force_foreign_changes: true
        checkmk_agent_host_ip: "{{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}"
        checkmk_agent_host_name: "{{ inventory_hostname_short }}"
        checkmk_agent_mode: pull
        checkmk_agent_protocol: https
        # checkmk_agent_secret - provided via CLI
        checkmk_agent_server: [REDACTED]
        checkmk_agent_server_ip: [REDACTED]
        checkmk_agent_server_protocol: https
        checkmk_agent_site: [REDACTED]
        checkmk_agent_tls: true
        checkmk_agent_user: automation
        checkmk_agent_version: "2.2.0p26"
    - name: Install, configure and register Checkmk agent
      ansible.builtin.include_role:
        name: checkmk.general.agent
```
- Execute the playbook: `ansible-playbook playbook_checkmk.yml -i [REDACTED], --extra-vars checkmk_agent_secret=[REDACTED]`

**Additional context**
For now, I work around this problem with just this tasks before including the role:
```yaml
- name: Move Checkmk host to the correct folder
  checkmk.general.host:
    name: "{{ checkmk_agent_host_name }}"
    folder: "{{ checkmk_agent_folder }}"
    state: present
    server_url: "{{ checkmk_agent_protocol }}://{{ checkmk_agent_server }}/"
    site: "{{ checkmk_agent_site }}"
    automation_user: "{{ checkmk_agent_user }}"
    automation_secret: "{{ checkmk_agent_secret }}"
```

**Comment by msekania** [comment]
@eliasp

It is not a bug! It is explicitly designed that way, (see also the error message!)

The problem is as follows:
You can set parameters both at folder level and at host level. The host then receives the so-called effective parameters.
What happens if I set the parameters and at the same time move the host to the new folder, with different parameters than the current folder?
In this case, it can easily lead to a situation where you expect a certain behavior but get something else.
To avoid this, it was intentionally split into two workflows, either set parameters or move the host, as it is also stated in the error message.

**Comment by eliasp** [comment]
I'm aware, that on the module level, that's the expected behavior.
But what's not expected, is seeing this behavior on the role level.

Including the `checkmk.general.agent` role and supplying the desired variables should never lead to this error message, but the separate handling of those things should be dealt with role-internally, using an approach similar to my workaround.

**Comment by msekania** [comment]
@robin-checkmk,

https://github.com/Checkmk/ansible-collection-checkmk.general/blob/2188a6dc031a021ba9148e77877b002dcb82b41d/roles/agent/tasks/Linux.yml#L54C1-L72C29

The following should do the job
just split it in two tasks (first without `attributes` fild)
```yaml
- name: "{{ ansible_system }}: Create host on server."
  checkmk.general.host:
    server_url: "{{ checkmk_agent_server_protocol }}://{{ checkmk_agent_server }}:{{ checkmk_agent_server_port }}/"
    site: "{{ checkmk_agent_site }}"
    validate_certs: "{{ checkmk_agent_server_validate_certs | bool }}"
    automation_user: "{{ checkmk_agent_user }}"
    automation_secret: "{{ __checkmk_agent_auth }}"
    folder: "{{ checkmk_agent_folder | default(omit) }}"
    name: "{{ checkmk_agent_host_name }}"
    state: "present"
  become: false
  register: __checkmk_agent_create_result
  failed_when: |
    (__checkmk_agent_create_result.failed == true) and
    ("The host is already part of the specified target folder" not in __checkmk_agent_create_result.msg)
  delegate_to: "{{ checkmk_agent_delegate_api_calls }}"
  when: checkmk_agent_add_host | bool
  notify: "Activate changes"

- name: "{{ ansible_system }}: Create host on server."
  checkmk.general.host:
    server_url: "{{ checkmk_agent_server_protocol }}://{{ checkmk_agent_server }}:{{ checkmk_agent_server_port }}/"
    site: "{{ checkmk_agent_site }}"
    validate_certs: "{{ checkmk_agent_server_validate_certs | bool }}"
    automation_user: "{{ checkmk_agent_user }}"
    automation_secret: "{{ __checkmk_agent_auth }}"
    folder: "{{ checkmk_agent_folder | default(omit) }}"
    name: "{{ checkmk_agent_host_name }}"
    attributes: "{{ checkmk_agent_host_attributes }}"
    state: "present"
  become: false
  register: __checkmk_agent_create_result
  failed_when: |
    (__checkmk_agent_create_result.failed == true) and
    ("The host is already part of the specified target folder" not in __checkmk_agent_create_result.msg)
  delegate_to: "{{ checkmk_agent_delegate_api_calls }}"
  when: checkmk_agent_add_host | bool
  notify: "Activate changes"

```
