### ISSUE TITLE
[BUG] Server Site MKP management not working

### ISSUE THREAD

**Issue by rrinco** [Checkmk/ansible-collection-checkmk.general#777]
**Describe the bug**
When setting mkp_packages for a site it tries to install it by using `omd su {{ __site.name }} -c mkp add` but at least for CRE `-c` is just ignored and command hangs. Running the same command directly in the server shows `-c` does not run any command after it:
```console
[root@master ~]# omd su s010 -c mkp list
Last login: Wed May 14 13:54:15 UTC 2025 on pts/1
-bash: warning: setlocale: LC_ALL: cannot change locale (es_AR.UTF-8)
/bin/sh: warning: setlocale: LC_ALL: cannot change locale (es_AR.UTF-8)
/bin/sh: warning: setlocale: LC_ALL: cannot change locale (es_AR.UTF-8)
/bin/sh: warning: setlocale: LC_ALL: cannot change locale (es_AR.UTF-8)
-bash: warning: setlocale: LC_CTYPE: cannot change locale (es_AR.UTF-8)
-bash: warning: setlocale: LC_NUMERIC: cannot change locale (es_AR.UTF-8)
-bash: warning: setlocale: LC_TIME: cannot change locale (es_AR.UTF-8)
-bash: warning: setlocale: LC_COLLATE: cannot change locale (es_AR.UTF-8)
-bash: warning: setlocale: LC_MESSAGES: cannot change locale (es_AR.UTF-8)
locale: Cannot set LC_CTYPE to default locale: No such file or directory
locale: Cannot set LC_MESSAGES to default locale: No such file or directory
locale: Cannot set LC_COLLATE to default locale: No such file or directory
OMD[s010]:~$

```

**Component Name**

Component Name: sites/mkp

**Ansible Version**

```console
ansible [core 2.16.14]
  config file = /home/rrinco/git/infra-ar-dc/ansible/checkmk/ansible.cfg
  configured module search path = ['/home/rrinco/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/rrinco/.pyenv/versions/3.12.5/envs/ansible-2.16/lib/python3.12/site-packages/ansible
  ansible collection location = /home/rrinco/.ansible/collections:/usr/share/ansible/collections
  executable location = /home/rrinco/.pyenv/versions/ansible-2.16/bin/ansible
  python version = 3.12.5 (main, Aug 22 2024, 15:43:41) [GCC 11.4.0] (/home/rrinco/.pyenv/versions/3.12.5/envs/ansible-2.16/bin/python)
  jinja version = 3.1.6
  libyaml = True

```

**Checkmk Version and Edition**

```console
Checkmk Raw Edition 2.3.0p30
```

**Collection Version**

```console
$ # /home/rrinco/.ansible/collections/ansible_collections
Collection                               Version
---------------------------------------- -------
ansible.posix                            2.0.0  
ansible.utils                            6.0.0  
checkmk..ansible                         *      
checkmk.general                          5.8.0  
community.crypto                         2.23.0 
community.docker                         4.3.1  
community.general                        10.3.1 
community.library_inventory_filtering_v1 1.0.1  
community.mysql                          3.11.0 
community.vmware                         5.3.0

```

**To Reproduce**
1. Add a mkp_packages variables with correspondent values in a site checkmk_server_sites definition
2. Run playbook calling the role checkmk.general.server
4. Wait until task Install mkp packages

**Expected behavior**
MKP installed and enabled

**Actual behavior**
Task hangs:
```console
TASK [checkmk.general.server : Download MKP Packages.] *********************************************************************************************************************************
skipping: [master.s010.tt090.lan] => (item={'name': 'nut', 'version': '2.0.4', 'src': 'nut-2.0.4.mkp', 'installed': 'true', 'enabled': 'true'}) 
skipping: [master.s010.tt090.lan]

TASK [checkmk.general.server : Transfer MKP Packages.] *********************************************************************************************************************************
changed: [master.s010.tt090.lan] => (item={'name': 'nut', 'version': '2.0.4', 'src': 'nut-2.0.4.mkp', 'installed': 'true', 'enabled': 'true'})

TASK [checkmk.general.server : Install mkp packages.] **********************************************************************************************************************************
^C [ERROR]: User interrupted execution
```

**Minimum reproduction example**

```yaml
- name: Install and configure Checkmk server
  hosts: all
  gather_facts: true

  tasks:
    - name: Create Server
      tags: create-server
      block:
        - name: Install Checkmk and create Sites
          tags: create-server
          ansible.builtin.import_role:
            name: checkmk.general.server

---
checkmk_server_sites:
  - name: "{{ checkmk_site }}"
    version: "{{ checkmk_server_version }}"
    update_conflict_resolution: 'abort'
    omd_auto_restart: 'false'
    omd_config:
      - var: LIVESTATUS_TCP
        value: 'on'
      - var: LIVESTATUS_TCP_PORT
        value: "{{ checkmk_server_livestatus_tcp_port | default(6557) }}"
    state: started
    admin_pw: "{{ checkmk_server_admin_pass }}"
    mkp_packages:
      - name: 'nut'
        version: 2.0.4
        src: 'nut-2.0.4.mkp'
        installed: 'true'
        enabled: 'true'

```

**Additional context**
